pipeline {
    agent any

    
    stages {

        stage('Setup') {
            steps {
                sh '''
                    cd 03-lambda-deployment/
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install -r lambda-app/tests/requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd 03-lambda-deployment/
                    python3 -m venv venv
                    . venv/bin/activate
                    pytest   
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    cd 03-lambda-deployment/
                    sam build -t lambda-app/template.yaml
                '''
            }
        }
        stage('Deploy') {

            environment {
                AWS_ACCESS_KEY_ID = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }
            
            steps {
                sh '''
                    cd 03-lambda-deployment/
                    sam deploy -t lambda-app/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset
                    echo 'step finalized'
                '''
            }
        }
      
    }
}