pipeline {
    agent any

    
    stages {

        stage('Setup') {
            steps {
                sh "cd 03-lambda-deployment/"
                sh "python3 -m venv venv"
                sh ". venv/bin/active"
                sh "pip3 install -r lambda-app/tests/requirements.txt"
                echo "success-1"
            }
        }
        stage('Test') {
            steps {
                sh "cd 03-lambda-deployment/"
                sh "python3 -m venv venv"
                sh ". venv/bin/active"
                sh "pytest"
                echo "success-2"                
            }
        }

        stage('Build') {
            steps {
                sh "cd 03-lambda-deployment/"
                sh "sam build -t lambda-app/template.yaml"
                echo "success-3"
            }
        }
        stage('Deploy') {

            environment {
                AWS_ACCESS_KEY_ID = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }
            
            steps {
                sh "cd 03-lambda-deployment/"
                sh "sam deploy -t lambda-app/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset"
                echo "success-4"
            }
        }
      
    }
}