pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-server-ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh '''
                    cd  02-single-server-deployment/
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }
        stage('verify installation') {
                steps {
                    sh '''
                        cd 02-single-server-deployment/
                        pip freeze
                    '''
                }
        }
        stage('Test') {
                steps {
                    sh '''
                        cd 02-single-server-deployment/
                        echo "test complete"
                        . venv/bin/activate
                        pytest test_app.py
                    '''
                }
        }

        stage('Package code') {
            steps {
                sh '''
                    cd 02-single-server-deployment/
                    zip -r myapp.zip ./* -x '*.git*'
                    ls -lart
                '''
            }
        }

        stage('Deploy to Prod') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-key', keyFileVariable: 'MY_SSH_KEY', usernameVariable: 'username')]) {
                    sh '''
                    scp -i $MY_SSH_KEY -o StrictHostKeyChecking=no 02-single-server-deployment/myapp.zip  ${username}@${SERVER_IP}:/home/ec2-user/
                    ssh -i $MY_SSH_KEY -o StrictHostKeyChecking=no ${username}@${SERVER_IP} << EOF
                        unzip -o /home/ec2-user/myapp.zip -d /home/ec2-user/app/
                        source app/venv/bin/activate
                        cd /home/ec2-user/app/
                        # Recreate the virtual environment to ensure compatibility
                        rm -rf venv
                        python3 -m venv venv
                        source venv/bin/activate
                        pip install -r requirements.txt
                        # Restart the Flask service
                        sudo systemctl restart flask.service
EOF
                    '''
                }
            }
        }
       
        
       
        
    }
}